import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { AiFillFacebook, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import model from "../public/3d-model.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 transition-all duration-500 lg:px-20 dark:bg-gray-800">
        <section className="mb-6 min-h-screen">
          <nav className="py-10 mb-6 flex justify-between">
            <h1 className="font-burtons text-xl dark:text-white">
              mithil_hassan
            </h1>
            <ul className="flex items-center">
              <li
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl"
              >
                {darkMode ? (
                  <BsFillSunFill className=" text-yellow-200" />
                ) : (
                  <BsFillMoonStarsFill />
                )}
              </li>
              <li>
                <a
                  className="hidden bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 hover:brightness-90 transition-all duration-300 md:block"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Mithil Hassan
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Front-End Web Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 max-w-4xl mx-auto md:text-xl dark:text-gray-400">
              I am a freelancer. Working with core Javascript and it&#39;s
              framework specially React. Have hands-on experience in Html, Css,
              Bootstrap, Saas, Tailwind, Materialize, JavaScript, Jquery, React,
              Firebase and NextJs. Join me down below and let&#39;s get
              cracking.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.facebook.com/mithil.hassan.7/">
              <AiFillFacebook className=" cursor-pointer hover:text-gray-400 transition-all duration-300" />
            </a>
            <a href="#">
              <AiFillLinkedin className=" cursor-pointer  hover:text-gray-400 transition-all duration-300" />
            </a>
            <a href="https://github.com/MithilHassan">
              <AiFillGithub className=" cursor-pointer  hover:text-gray-400 transition-all duration-300" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 ">
            <Image src={model} layout="fill" objectFit="cover" alt="avatar" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Since the beginning of my journey as a freelance web developer,
              I&#39;ve done remote work for
              <span className="text-teal-500"> agencies </span>consulted for
              <span className="text-teal-500"> startups </span>and collaborated
              with talented people to create awesome dynamic and responsive
              websites.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700 ">
              <Image src={design} width={100} height={100} alt="" />
              <h2 className="text-2xl font-medium pt-8 pb-2 dark:text-white">
                Beautiful Designs
              </h2>
              <p className="py-2 dark:text-gray-400">
                Besides quality also work on elegant designs suited for your
                websites following core design theory.
              </p>
              <h4 className="py-4 text-teal-600 font-bold">Tools I Use</h4>
              <div className="flex flex-wrap justify-center gap-10">
                <p className="text-gray-800 font-medium dark:text-white">
                  PhotoShop
                </p>
                <p className="text-gray-800 font-medium dark:text-white">
                  Illustrator
                </p>
                <p className="text-gray-800 font-medium dark:text-white">
                  Figma
                </p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <Image src={code} width={100} height={100} alt="" />
              <h2 className="text-2xl font-medium pt-8 pb-2 dark:text-white">
                Code
              </h2>
              <p className="py-2 dark:text-gray-400">
                Use simple, re-useable and SEO friendly code to build fast and
                user friendly website.
              </p>
              <h4 className="py-4 text-teal-600 font-bold">Tools I use</h4>
              <div className="flex flex-wrap justify-center gap-10">
                <p className="text-gray-800 font-medium dark:text-white">
                  Visual Studio Code
                </p>
                <p className="text-gray-800 font-medium dark:text-white">
                  GitHub
                </p>
                <p className="text-gray-800 font-medium dark:text-white">
                  Chrome&#39;s DevTools
                </p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <Image src={consulting} width={100} height={100} alt="" />
              <h2 className="text-2xl font-medium pt-8 pb-2 dark:text-white">
                Consulting
              </h2>
              <p className="py-2 dark:text-gray-400">
                Work with clients to promote the success of their business by
                providing practical suggestions.
              </p>
              <h4 className="py-4 text-teal-600 font-bold">Tools I use</h4>
              <div className="flex flex-wrap justify-center gap-10">
                <p className="text-gray-800 font-medium dark:text-white">
                  Zoom
                </p>
                <p className="text-gray-800 font-medium dark:text-white">
                  Calendly
                </p>
                <p className="text-gray-800 font-medium dark:text-white">
                  QuickBooks
                </p>
                <p className="text-gray-800 font-medium dark:text-white">
                  Mailchimp
                </p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web3}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web4}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web5}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web6}
                  alt=""
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
